[router]
parent = 'internet'

[bowser]
parent = 'switch'

[donkeykong]
parent = 'switch'

[peach]
parent = 'switch'

[wifi]
parent = 'switch'

[workstation]
parent = 'router'

[switch]
parent = 'router'

[internet]
parent = ''

[phone]
parent = 'wifi'